name: GitHub Profile Summary CI

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the build on the latest version of Ubuntu
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  #
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure your requirements.txt is present with all dependencies

    # Step 4: Build and deploy 
    - name: Build and deploy
      run: |
        echo "Build and deploy steps go here"
        # You can add deployment commands here if you're deploying to a server or a platform (like Heroku)
