name: GitHub Profile Summary CI & Local Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure your requirements are correctly listed in requirements.txt
    
    # Step 4: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: 'latest'
    
    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t github-profile-summary .
    
    # Step 6: Run the Docker container to simulate local deployment
    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 github-profile-summary  # Ensure this port matches your app's listening port
    
    # Step 7: Check if the app is running (for testing)
    - name: Check if the app is running
      run: |
        curl http://localhost:8000  # Ensure this port is correct and matches the Docker run command
